export const SERVICES_SOLUTIONS = [
  {
    slug: "prospection-ia",
    name: "Prospection IA",
    description: "Ciblage IA par secteur et zone, enrichissement automatique, scoring leads, intégration CRM.",
    serviceHref: "/services/trouver-prospects",
    price: "99",
  },
  {
    slug: "site-web",
    name: "Site Web Moderne",
    description: "Site web rapide, SEO classique + SEO IA, mobile-first, templates sectoriels, livré en 14 jours.",
    serviceHref: "/services/site-web-moderne",
    price: "99",
  },
  {
    slug: "automatisation",
    name: "Automatisation RPA",
    description: "Workflows sur mesure : relances email, CRM, facturation, reporting, dashboard KPI. 200+ intégrations.",
    serviceHref: "/services/automatiser-relances",
    price: "149",
  },
  {
    slug: "integration-ia",
    name: "Intégration IA",
    description: "Chatbot site/WhatsApp, agents IA métier, RAG sur vos données, connexion outils existants.",
    serviceHref: "/services/integration-ia",
    price: "199",
  },
  {
    slug: "digital-workplace",
    name: "Digital Workplace",
    description: "Bureau virtuel gamifié pour centraliser vos outils métier dans un seul espace.",
    serviceHref: "/services/digital-workplace",
    price: "199",
  },
  {
    slug: "nixie-pulse",
    name: "Nixie Pulse",
    description: "Dashboard KPI physique connecté avec tubes Nixie soviétiques. Affichage temps réel de vos données métier.",
    serviceHref: "/services/nixie-pulse",
    price: "990",
  },
] as const;

export const SECTEURS = [
  {
    slug: "cabinet-conseil",
    name: "Cabinet de conseil",
    problemType: "Prospection chronophage, dépendance au bouche-à-oreille, suivi client manuel",
    solutions: {
      "prospection-ia": "Identifiez automatiquement les entreprises qui correspondent à votre expertise. Ciblage par secteur, taille et zone géographique. Enrichissement des contacts décideurs.",
      "site-web": "Un site qui positionne votre expertise et génère des leads qualifiés. Pages par domaine de compétence, cas clients, prise de RDV intégrée.",
      "automatisation": "Automatisez le suivi de vos missions, les relances prospects, le reporting client et la facturation récurrente.",
      "integration-ia": "Un assistant IA qui qualifie vos leads entrants, répond aux questions fréquentes et prépare vos rendez-vous avec le contexte client.",
      "digital-workplace": "Un bureau virtuel gamifié où vos consultants retrouvent CRM, projets, documents et messagerie dans un seul espace structuré.",
    },
    faqCount: 3,
  },
  {
    slug: "agence-marketing",
    name: "Agence marketing",
    problemType: "Trop de process manuels, reporting chronophage, prospection passive",
    solutions: {
      "prospection-ia": "Prospectez les PME et ETI qui n'ont pas encore d'agence. Ciblage par secteur, CA et présence digitale. Enrichissement LinkedIn et email.",
      "site-web": "Un site portfolio qui convertit : cas clients, résultats chiffrés, formulaire de brief, SEO sur vos expertises clés.",
      "automatisation": "Automatisez vos reportings clients, vos relances de devis, la compilation de KPI multi-plateformes et la facturation.",
      "integration-ia": "Un chatbot qui qualifie les briefs entrants. Des agents IA pour la veille concurrentielle, l'analyse de données et la rédaction.",
      "digital-workplace": "Centralisez briefs, projets clients, reporting et communication d'équipe dans un bureau virtuel dédié à votre agence.",
    },
    faqCount: 3,
  },
  {
    slug: "cabinet-comptable",
    name: "Cabinet comptable",
    problemType: "Relances manuelles, deadlines serrées, collecte de pièces chronophage",
    solutions: {
      "prospection-ia": "Identifiez les TPE/PME sans expert-comptable ou insatisfaites. Ciblage par zone, secteur et taille. Enrichissement email du dirigeant.",
      "site-web": "Un site professionnel qui rassure : expertises, équipe, prise de RDV en ligne, FAQ sur les obligations comptables.",
      "automatisation": "Automatisez les relances de pièces comptables, le suivi des échéances fiscales, les rappels clients et la facturation.",
      "integration-ia": "Un chatbot qui répond aux questions comptables courantes de vos clients. Un agent IA qui pré-catégorise les pièces reçues.",
      "digital-workplace": "Un espace unifié pour vos collaborateurs : dossiers clients, échéances fiscales, messagerie et KPI dans un bureau virtuel structuré.",
    },
    faqCount: 3,
  },
  {
    slug: "esn",
    name: "ESN / SSII",
    problemType: "Prospection massive, qualification faible, suivi des missions complexe",
    solutions: {
      "prospection-ia": "Identifiez les entreprises qui recrutent des profils tech. Ciblage par stack technique, taille et localisation. Scoring par potentiel de mission.",
      "site-web": "Un site qui met en avant vos compétences techniques, vos références et vos consultants disponibles. SEO sur les technologies clés.",
      "automatisation": "Automatisez le matching consultant/mission, les relances commerciales, le suivi d'intercontrat et le reporting d'activité.",
      "integration-ia": "Un agent IA qui analyse les appels d'offres, matche les profils consultants et prépare les réponses techniques.",
      "digital-workplace": "Gérez vos consultants, missions et intercontrats dans un bureau virtuel avec CRM, projets et KPI centralisés.",
    },
    faqCount: 3,
  },
  {
    slug: "coach-consultant",
    name: "Coach / Consultant",
    problemType: "Pas de système de leads, dépendance au réseau, site web basique ou absent",
    solutions: {
      "prospection-ia": "Identifiez les entreprises qui ont besoin de vos compétences. Ciblage par problématique métier, taille et secteur.",
      "site-web": "Un site qui vous positionne comme expert : page de méthode, témoignages, calendrier de RDV, blog SEO sur votre thématique.",
      "automatisation": "Automatisez votre séquence de prospection, vos relances, votre facturation et le suivi de vos clients.",
      "integration-ia": "Un chatbot qui qualifie vos visiteurs et prend des RDV. Un agent IA qui prépare vos sessions avec le contexte client.",
      "digital-workplace": "Un bureau virtuel personnel avec votre agenda, suivi clients, contenus et facturation — tout en un seul espace.",
    },
    faqCount: 3,
  },
  {
    slug: "artisan",
    name: "Artisan / TPE",
    problemType: "Pas de visibilité en ligne, suivi client au papier ou par SMS, pas de site web",
    solutions: {
      "prospection-ia": "Identifiez les prospects locaux qui cherchent vos services. Ciblage par zone géographique et type de besoin.",
      "site-web": "Un site vitrine professionnel avec vos réalisations, zone d'intervention, devis en ligne. Visible sur Google Maps et les recherches locales.",
      "automatisation": "Automatisez vos devis, relances, rappels de chantier et facturation. Fini les oublis et le papier.",
      "integration-ia": "Un chatbot WhatsApp qui prend les demandes de devis 24/7 et les organise automatiquement dans votre planning.",
      "digital-workplace": "Un espace simple pour gérer vos devis, chantiers, factures et communication client sans jongler entre 5 applis.",
    },
    faqCount: 3,
  },
  {
    slug: "restaurant",
    name: "Restaurant / Hôtellerie",
    problemType: "Site non trouvable, pas de réservation en ligne, avis non gérés",
    solutions: {
      "prospection-ia": "Identifiez les entreprises locales pour des partenariats B2B (événements, repas d'affaires, séminaires).",
      "site-web": "Un site avec menu, réservation en ligne, galerie photos, avis Google intégrés. Optimisé pour le référencement local.",
      "automatisation": "Automatisez les confirmations de réservation, les rappels clients, les demandes d'avis post-visite et le suivi fournisseurs.",
      "integration-ia": "Un chatbot de réservation sur votre site et WhatsApp. Un agent IA qui gère les demandes d'événements et les menus personnalisés.",
      "digital-workplace": "Centralisez réservations, planning équipe, commandes fournisseurs et communication interne dans un bureau virtuel adapté à l'hôtellerie-restauration.",
    },
    faqCount: 3,
  },
  {
    slug: "avocat-notaire",
    name: "Avocat / Notaire",
    problemType: "Site générique, aucun lead organique, image en ligne négligée",
    solutions: {
      "prospection-ia": "Identifiez les entreprises qui ont besoin de conseil juridique : créations, litiges, conformité. Ciblage par secteur et événements.",
      "site-web": "Un site qui reflète votre expertise : domaines de droit, équipe, publications, prise de RDV confidentielle. SEO sur vos spécialités.",
      "automatisation": "Automatisez le suivi des dossiers, les relances de pièces, les rappels d'audience et la facturation des actes.",
      "integration-ia": "Un chatbot confidentiel qui pré-qualifie les demandes de consultation et oriente vers le bon expert du cabinet.",
      "digital-workplace": "Un espace sécurisé pour gérer dossiers, échéances, communication interne et suivi client — adapté aux contraintes de confidentialité.",
    },
    faqCount: 3,
  },
  {
    slug: "immobilier",
    name: "Agence immobilière",
    problemType: "Prospection terrain uniquement, suivi manuel des mandats, site vitrine peu performant",
    solutions: {
      "prospection-ia": "Identifiez les propriétaires susceptibles de vendre : changements de vie, successions, investisseurs. Ciblage par zone et type de bien.",
      "site-web": "Un site avec listings de biens, fiches détaillées, estimateur en ligne, formulaires de contact par bien. SEO local optimisé.",
      "automatisation": "Automatisez les alertes acquéreurs, les relances mandats, le matching biens/acheteurs et le reporting d'activité.",
      "integration-ia": "Un chatbot qui qualifie les demandes (achat/vente/location), propose les biens correspondants et prend les RDV de visite.",
      "digital-workplace": "Gérez mandats, biens, visites et communication d'équipe dans un bureau virtuel immobilier avec pipeline et KPI.",
    },
    faqCount: 3,
  },
  {
    slug: "e-commerce",
    name: "E-commerce / Boutique en ligne",
    problemType: "Trafic faible, pas de rétention client, processus manuels de gestion",
    solutions: {
      "prospection-ia": "Identifiez les partenaires B2B, revendeurs et influenceurs de votre niche. Ciblage par secteur et audience.",
      "site-web": "Un site e-commerce optimisé : fiches produits SEO, tunnel de conversion, pages catégories, blog produit.",
      "automatisation": "Automatisez le suivi de commandes, les relances panier abandonné, les emails post-achat et la gestion de stock.",
      "integration-ia": "Un chatbot qui guide l'achat, répond aux questions produit et gère le SAV. Un agent IA pour les recommandations personnalisées.",
      "digital-workplace": "Centralisez commandes, stock, SAV, marketing et communication d'équipe dans un bureau virtuel e-commerce.",
    },
    faqCount: 3,
  },
] as const;

export type ServiceSolution = (typeof SERVICES_SOLUTIONS)[number];
export type Secteur = (typeof SECTEURS)[number];
